### ISSUE TITLE
Flavor standards file schema changed

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/standards#216]
@garloff I noticed during "finishing" the flavor manager, that the original agreed file structure diverged a lot. The initial file structure required values for the names to make the flavor manager as generic as possible: https://github.com/osism/openstack-flavor-manager/blob/main/flavors.yaml. Why was this changed to "only" the names?

**Comment by garloff** [comment]
Tim,

Not sure with whom you agreed on w.r.t. the format of the flavor list file. I can't remember it, sorry. 

I would *not* change the primary list of mandatory flavors from what it currently is.
The names contain *all* of the needed information and the rest would be duplication which is never a good thing.

What I could easily do is to create a tool that generates a secondary file in the format that you desire.

Works for you?

**Comment by garloff** [comment]
Sidenote: SCSx- as prefix does not seem to have universal support. I have not written an ADR draft to start the discussion, but I did hear hefty opposition from one of our providers, so I prioritized other things first (that will have better chances of being successful).

**Comment by garloff** [comment]
Alternative to generating a file in your desired format would be to have you call into `flavor-name-check.py` directly. Would some kind of agreement to avoid interfaces that you depend on being broken. So I guess a generated yaml file is the safer approach.

**Comment by fkr** [comment]
> Sidenote: SCSx- as prefix does not seem to have universal support. I have not written an ADR draft to start the discussion, but I did hear hefty opposition from one of our providers, so I prioritized other things first (that will have better chances of being successful).

Where was that voiced? I've not heard that yet, so I'm very curious about that.

**Comment by tibeer** [comment]
Good that we have this discussion than. The initial idea was to make the flavor manager as generic as possible. Yes, I could create logic that automatically "guesses" the t-shirt size of each flavor. But this would prevent future flavors like "SCS-standard-S", "SCS-standard-XXL", etc. Making it generic would also allow us to bring these flavors easily to other cloud solutions (may it be AWS, VMWare, what have you). Even if they are not sovereign clouds, consumers (not CSPs) of SCS standards can heavily profit from unified flavor names when it comes to inter-cloud migrations. They would not need to recreate logic that guesses the dimensions of a flavor but may instead just read the values.

```yaml
[...]
  - name: SCS-1L:1
    cpus: 1
    ram: 1024
    disk: 0
[...]
```

How does this sound to you? :)

**Comment by garloff** [comment]
> Where was that voiced? I've not heard that yet, so I'm very curious about that.

@frosty-geek voiced not liking the idea of having several prefixes.

**Comment by garloff** [comment]
> They would not need to recreate logic that guesses the dimensions of a flavor but may instead just read the values.
> 
> ```yaml
> [...]
>   - name: SCS-1L:1
>     cpus: 1
>     ram: 1024
>     disk: 0
> [...]
> ``` 

I am completely sympathetic to your desire.
As the name contains all the information already, I would continue to see the pure list of names as the primary source of information and would generate the file in your desired format from that.
I would add the option to flavor name check and someone could build a github action to generate the resulting yaml from this...

**Comment by frosty-geek** [comment]
> > Where was that voiced? I've not heard that yet, so I'm very curious about that.
> 
> @frosty-geek voiced not liking the idea of having several prefixes.

True, we've had a "huge" amount (~180) of flavors and had to revert that chance as it found no broader acceptance. One of the issues was the lack of pagination within Horizon which made the usage very slow.

But I don't fully understand the discussion tbh... Are we talking about exposing the technical details to some format as well as generating the name according to the standard?

**Comment by garloff** [comment]
@frosty-geek: There was a discussion whether we should differentiate flavors between those starting with:
* `SCS-`: Only the (currently 26) flavors that must be available on all compliant SCS IaaS clouds
* `SCSx-`: All flavors that follow the systematic SCS naming approach, but not part of the mandatory list and thus likely only available on a subset of compliant SCS IaaS clouds
* All others.

This makes it very easy for users to avoid flavors that might limit portability.

**Comment by garloff** [comment]
Tim, this little helper would produce the input that you need for the openstack-flavor-manager.
It allows us to keep the mandatoryFlavors.yaml very short and readable (if you are used to parse the SCS- names) and avoids duplicate (and potentially contradicting) information.

**Comment by garloff** [comment]
@itrich : Would it be hard to have a github action that builds the flavor list in the flavor-manager format whenever things change?

**Comment by itrich** [comment]
> @itrich : Would it be hard to have a github action that builds the flavor list in the flavor-manager format whenever things change?

No, we could easily create such a workflow that also automagically commits any changes.

**Comment by garloff** [comment]
Fixed by merged #227.

**Comment by tibeer** [comment]
Reopened. Github workflow is still not in place to generate the desired file.

**Comment by itrich** [comment]
I need some further information on where the generated file should be located and how we make sure that the auto-generated file won't be edited by users.

**Comment by tibeer** [comment]
The second part is easy: Just trigger the workflow to generate the file on changes on a) the "small" file and b) once there are changes on the auto-generated file itself. This would automagically "revert" manual user changes.

For the first part: I would suggest to place it next to the original file with a name like `SCS-Spec.MandatoryFlavors.autogenerated.yaml`
